name: prd gnoswap push gnoswap-tx-indexer v2

on:
  push:
    branches:
      - main
  workflow_dispatch:

permissions:
  contents: write
  id-token: write
jobs:
  prd_gnoswap_tx_indexer:
    name: Run tx-indexer app
    uses: ./.github/workflows/app_template.yml
    with:
      app-name: 'tx-indexer'
      env: 'prd-gnoswap-v2'
    secrets:
      AWS_IAM_OIDC: ${{ secrets.AWS_IAM_OIDC }}
      PAT_TOKEN: ${{ secrets.PAT_TOKEN }}
      REGION: ${{ secrets.PRD_REGION_V2 }}
